// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#include<bits/stdc++.h>

using namespace std;

int main(){
    // vector<long long> v;
    int * v = new int[4000001];
    v[0] = 1;
    v[1] = 2;
    double sum = 0;
    // long long int i = 2;
    // while(1){
    //     v[i] = v[i-1] + v[i-2];
    //     if(v[i] > 4000000){
    //         break;
    //     }
    //     i++;
    // }

    for(int i = 0; v[i] < 1000; i++){
        v[i] = v[i-1] + v[i-2];
    }
    int size = sizeof(v)/sizeof(v[0]);
    long long ans = 0;
    for(int i = 0; i < size; i++){
        if(v[i]%2 == 0){
            ans += v[i];
        }
    }

    cout << ans << endl;
}